version: '2'
services:
    app:
        container_name: 'cache-gateway'
        image: registry.cn-hangzhou.aliyuncs.com/yab/intersystems-cachedb:gateway
        ports:
          - 8088:80
        mem_limit: 100mb
        memswap_limit: 100mb
        domainname: local.weblocus
        links:
            - cache
        networks:
            app_net:
                ipv4_address: 192.168.95.20
    cache:
        container_name: 'cache-database'
        image: registry.cn-hangzhou.aliyuncs.com/yab/intersystems-cachedb:database
        ports:
          - 61972:1972
        command: mkdir /usr/cachesys/mgr/data-external
        mem_limit: 200mb
        memswap_limit: 200mb
        networks:
            app_net:
                ipv4_address: 192.168.95.21
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.95.0/24
        gateway: 192.168.95.2
